# Generated by Django 3.1.3 on 2024-01-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0022_questionanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('code', models.CharField(max_length=26, primary_key=True, serialize=False)),
                ('count', models.CharField(max_length=1000)),
                ('course', models.CharField(max_length=1000)),
                ('year_level', models.CharField(max_length=1000)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
