# Generated by Django 3.1.3 on 2024-01-18 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0023_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
