# Generated by Django 3.1.3 on 2024-01-18 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0024_delete_curso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
