# Generated by Django 3.1.3 on 2024-01-18 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0026_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
